// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTD3qvxFYd5EeWVurblHZrMqqWqFZ5gYM',
    appId: '1:270405529120:web:8b31dc401da374b0f75645',
    messagingSenderId: '270405529120',
    projectId: 'flutter-test-d2784',
    authDomain: 'flutter-test-d2784.firebaseapp.com',
    storageBucket: 'flutter-test-d2784.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQFwwH7r8OuPK0AL4ltbcp3A6-TwvjK_4',
    appId: '1:270405529120:android:e80ff4ba7985bb0df75645',
    messagingSenderId: '270405529120',
    projectId: 'flutter-test-d2784',
    storageBucket: 'flutter-test-d2784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Mcg6VnBgGuyf_YgzKnsHdvUkwCLFfEw',
    appId: '1:270405529120:ios:1b9be84f74e8f7fef75645',
    messagingSenderId: '270405529120',
    projectId: 'flutter-test-d2784',
    storageBucket: 'flutter-test-d2784.appspot.com',
    iosClientId: '270405529120-orgt16l1gearnsr2bhrn08vjuau66cmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Mcg6VnBgGuyf_YgzKnsHdvUkwCLFfEw',
    appId: '1:270405529120:ios:1b9be84f74e8f7fef75645',
    messagingSenderId: '270405529120',
    projectId: 'flutter-test-d2784',
    storageBucket: 'flutter-test-d2784.appspot.com',
    iosClientId: '270405529120-orgt16l1gearnsr2bhrn08vjuau66cmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginTaxi',
  );
}
